// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package things

import (
	"context"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			FindByIDFunc: func(ctx context.Context, thingID string) (Thing, error) {
//				panic("mock out the FindByID method")
//			},
//			FindRelatedThingsFunc: func(ctx context.Context, thingID string) ([]Thing, error) {
//				panic("mock out the FindRelatedThings method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// FindByIDFunc mocks the FindByID method.
	FindByIDFunc func(ctx context.Context, thingID string) (Thing, error)

	// FindRelatedThingsFunc mocks the FindRelatedThings method.
	FindRelatedThingsFunc func(ctx context.Context, thingID string) ([]Thing, error)

	// calls tracks calls to the methods.
	calls struct {
		// FindByID holds details about calls to the FindByID method.
		FindByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ThingID is the thingID argument value.
			ThingID string
		}
		// FindRelatedThings holds details about calls to the FindRelatedThings method.
		FindRelatedThings []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ThingID is the thingID argument value.
			ThingID string
		}
	}
	lockFindByID          sync.RWMutex
	lockFindRelatedThings sync.RWMutex
}

// FindByID calls FindByIDFunc.
func (mock *ClientMock) FindByID(ctx context.Context, thingID string) (Thing, error) {
	if mock.FindByIDFunc == nil {
		panic("ClientMock.FindByIDFunc: method is nil but Client.FindByID was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ThingID string
	}{
		Ctx:     ctx,
		ThingID: thingID,
	}
	mock.lockFindByID.Lock()
	mock.calls.FindByID = append(mock.calls.FindByID, callInfo)
	mock.lockFindByID.Unlock()
	return mock.FindByIDFunc(ctx, thingID)
}

// FindByIDCalls gets all the calls that were made to FindByID.
// Check the length with:
//
//	len(mockedClient.FindByIDCalls())
func (mock *ClientMock) FindByIDCalls() []struct {
	Ctx     context.Context
	ThingID string
} {
	var calls []struct {
		Ctx     context.Context
		ThingID string
	}
	mock.lockFindByID.RLock()
	calls = mock.calls.FindByID
	mock.lockFindByID.RUnlock()
	return calls
}

// FindRelatedThings calls FindRelatedThingsFunc.
func (mock *ClientMock) FindRelatedThings(ctx context.Context, thingID string) ([]Thing, error) {
	if mock.FindRelatedThingsFunc == nil {
		panic("ClientMock.FindRelatedThingsFunc: method is nil but Client.FindRelatedThings was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		ThingID string
	}{
		Ctx:     ctx,
		ThingID: thingID,
	}
	mock.lockFindRelatedThings.Lock()
	mock.calls.FindRelatedThings = append(mock.calls.FindRelatedThings, callInfo)
	mock.lockFindRelatedThings.Unlock()
	return mock.FindRelatedThingsFunc(ctx, thingID)
}

// FindRelatedThingsCalls gets all the calls that were made to FindRelatedThings.
// Check the length with:
//
//	len(mockedClient.FindRelatedThingsCalls())
func (mock *ClientMock) FindRelatedThingsCalls() []struct {
	Ctx     context.Context
	ThingID string
} {
	var calls []struct {
		Ctx     context.Context
		ThingID string
	}
	mock.lockFindRelatedThings.RLock()
	calls = mock.calls.FindRelatedThings
	mock.lockFindRelatedThings.RUnlock()
	return calls
}
